name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    runs-on: runner-scale-set-cp
    steps:
      - run: echo "🎉 This job uses runner scale set runners!"
