name: 'simple-test-lint'

on:
  push:
    branches:
      - 'main'
      - 'test-workflow'
  pull_request:
    branches:
      - 'main'
      - 'test-workflow'
  workflow_dispatch:
jobs:
  test:
    runs-on: runner-scale-set-cp
    steps:
      - uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test


